# Generated by Django 3.2.3 on 2021-05-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficheiros2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('resources', models.FileField(upload_to='resources/files')),
            ],
        ),
        migrations.CreateModel(
            name='Ficheiros3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('resources', models.FileField(upload_to='resources/files')),
            ],
        ),
        migrations.CreateModel(
            name='Ficheiros4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('resources', models.FileField(upload_to='resources/files')),
            ],
        ),
        migrations.CreateModel(
            name='Ficheiros5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('resources', models.FileField(upload_to='resources/files')),
            ],
        ),
        migrations.RenameModel(
            old_name='Ficheiros',
            new_name='Ficheiros1',
        ),
    ]
