# Generated by Django 3.2.3 on 2021-05-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210519_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ficheiros2',
            new_name='Ficheiros',
        ),
        migrations.DeleteModel(
            name='Ficheiros1',
        ),
        migrations.DeleteModel(
            name='Ficheiros3',
        ),
        migrations.DeleteModel(
            name='Ficheiros4',
        ),
        migrations.DeleteModel(
            name='Ficheiros5',
        ),
    ]
