# Generated by Django 3.2.3 on 2021-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210519_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheiros',
            name='subject',
            field=models.CharField(default='ihc', max_length=100),
            preserve_default=False,
        ),
    ]
