# Generated by Django 3.2.3 on 2021-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210526_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=123, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
