# Generated by Django 3.2.3 on 2021-05-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210526_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsSubdject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('subject', models.CharField(max_length=4)),
            ],
        ),
    ]
