# Generated by Django 3.2.3 on 2021-05-31 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_ficheiros_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheiros',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 17, 53, 16, 463652, tzinfo=utc)),
        ),
    ]
