# Generated by Django 3.2.3 on 2021-05-31 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_ficheiros_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheiros',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 17, 54, 5, 282031)),
        ),
    ]
