# Generated by Django 3.2.3 on 2021-05-31 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_ficheiros_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheiros',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 31, 17, 57, 18, 296819)),
        ),
    ]
