# Generated by Django 3.2.3 on 2021-06-14 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_ficheiros_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheiros',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 14, 14, 6, 48, 195416)),
        ),
    ]
